spring:
  datasource:
    hikari:
      username: user
      password: password
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/library
      connection-timeout: 20000
      minimum-idle: 100
      maximum-pool-size: 100
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
    url: jdbc:postgresql://localhost:5432/library
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        generate_statistics: true
        order_inserts: true
        order_updates: true
server:
  port: 8888

logging:
  level:
    org:
      INFO
    com:
      example:
        INFO